name: Lint and Build/Push Docker Image

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  flake8:  # Исправленное имя джобы
    name: Lint with Flake8 # Добавляем имя для понятности в UI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Flake8
        run: flake8 .  # Проверяет весь текущий каталог
    
  build:
    runs-on: ubuntu-latest
    needs: flake8 # Зависимость от flake8 джобы (правильное имя)

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Git Version
        id: git_version
        run: echo "::set-output name=version::$(git rev-parse --short HEAD)"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: . # Укажите путь к контексту сборки (где Dockerfile)
          dockerfile: ./Dockerfile # Явное указание Dockerfile (если не в корне)
          push: true
          tags: |
            antonozavr/testrepo:${{ steps.git_version.outputs.version }}
            antonozavr/testrepo:latest
          cache-from: type=dockerhub,name=antonozavr/testrepo:cache
          cache-to: type=dockerhub,name=antonozavr/testrepo:cache,mode=max
