name: Lint with Flake8

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  flake8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Flake8
        run: flake8 .  # Проверяет весь текущий каталог

# Собрать и отправить образ приложения на DockerHub
build:
runs-on: ubuntu-latest
needs: flake8-check
steps:
- name: Check out the repo
# Проверка доступности репозитория Docker Hub для workflow
uses: actions/checkout@v2
- name: Set up Docker Buildx
# Вызов сборщика контейнеров docker
uses: docker/setup-buildx-action@v1
- name: Login to Docker
# Запуск скрипта авторизации на Docker Hub
uses: docker/login-action@v1
with:
username: ${{ secrets.DOCKER_USERNAME }}
password: ${{ secrets.DOCKER_PASSWORD }}
- name: Push to Docker Hub
# Пуш образа в Docker Hub
uses: docker/build-push-action@v2
with:
push: true
tags: antonzavr/testrepo:latest

